parameters:
  - name: agentPool
    type: object
    default:
      name: 'agentpoolvmtemplate'
  - name: pipelineTemplate
    type: string
    default: 'master'
  - name: 'successImageTag'
    displayName: 'Input QAs Success tag'
    type: string

resources:
  repositories:
    - repository: azure-build-pipeline
      type: git
      name: KCB-DevOps/azure-build-pipeline
      ref: ${{ parameters.pipelineTemplate }}

trigger:
  - none

variables:
  - group: kcb-global-pipeline-variables
  - name: openshiftProjectName
    value: 'kekcb-recontool-portal'
  - name: openshiftProject
    value: 'kcb-recontool-core-v1'

stages:
  - template: /uat-tasks/stages/stage-selector-kcb-bss.yml@azure-build-pipeline
    parameters:
      service: '${{ variables.openshiftProject }}'
      successImageTag: ${{ parameters.successImageTag }}