parameters:
  - name: agentPool
    type: object
    default:
      name: 'KCB Default Agent Pool'
  - name: pipelineTemplate
    type: string
    default: 'master'
  - name: successImageTag
    type: string

resources:
  repositories:
    - repository: azure-build-pipeline
      type: git
      name: KCB-DevOps/azure-build-pipeline
      ref: ${{ parameters.pipelineTemplate }}

trigger: none

variables:
  - group: kcb-global-pipeline-variables
  - name: openshiftProjectName
    value: 'kekcb-recontool-portal'
  - name: openshiftProject
    value: 'kcb-mpesa-redeem-savings-v2'

stages:
  - template: /stages/release-pipeline-kcb_bss.yml@azure-build-pipeline
    parameters:
      openShiftProjectName: '${{ variables.openshiftProjectName }}'
      successImageTag: '${{ parameters.successImageTag }}'
      serviceName: '${{ variables.openshiftProject }}'
      mavenServiceConnections: 'KCB-DEV'